"""initial

Revision ID: 64eba5824a44
Revises: 
Create Date: 2025-12-15 10:50:31.899624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64eba5824a44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=True),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('modo', sa.String(length=20), nullable=False),
    sa.Column('dificuldade', sa.String(length=20), nullable=False),
    sa.Column('palavra', sa.String(length=100), nullable=False),
    sa.Column('letras_erradas', sa.String(length=20), nullable=True),
    sa.Column('letras_certas', sa.String(length=20), nullable=True),
    sa.Column('tentativas_restantes', sa.Integer(), nullable=True),
    sa.Column('rodada_atual', sa.Integer(), nullable=True),
    sa.Column('rounds_total', sa.Integer(), nullable=True),
    sa.Column('rounds_completed', sa.Integer(), nullable=True),
    sa.Column('wins_p1', sa.Integer(), nullable=True),
    sa.Column('wins_p2', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('vencedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vencedor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('users')
    # ### end Alembic commands ###
